### PR TITLE
Add new Birkbeck logo

### PR DESCRIPTION
**Pull request by mattandrews**
cc @jamesoram @feedmypixel 

Nothing major, just changes their logo (as requested).

### CODE REVIEW

**Comment by mattandrews** [comment]
Tried to be clever and use `git rebase` here to make my commit history look better, but instead it resulted in two further commits. Doubtless @rtyley is gnashing his teeth and wailing in agony somewhere near Greenwich...

**Comment by jamesoram** [comment]
:+1:

**Comment by davidrapson** [comment]
I get the following in the diff:



Should the logo still have transparency?

**Comment by mattandrews** [comment]
No, it's specifically meant to have this black background (that's their official colour). Wouldn't want the white to be transparent now either.

**Comment by davidrapson** [comment]
Ah fair enough :+1:

**Pull request merged**
