### PR TITLE
Add event provider: Central Saint Martins

### PR DESCRIPTION
**Pull request by mattandrews**
Adds another provider:

screen shot 2015-02-17 at 10 44 26

### CODE REVIEW

**Comment by mattandrews** [comment]
cc @jamesoram

**Comment by mattandrews** [comment]
Oh wait, @jamesoram isn't here... can someone else sanity check this? They need it out ASAP! cc @jennysivapalan / @feedmypixel / @davidrapson

**Comment by davidrapson** [comment]
:+1:

**Comment by jennysivapalan** [comment]
:+1: :art:

**Comment by mattandrews** [comment]
:mortar_board:

**Pull request merged**
