### PR TITLE
Add new provider and logo

### PR DESCRIPTION
**Pull request by mattandrews**
Adds the Photographer's Gallery as a provider. Looks like this:

screen shot 2015-03-24 at 14 37 35

cc @davidrapson / @jennysivapalan

### CODE REVIEW

**Comment by davidrapson** [comment]
:+1:

(Wish we had a better approach for these logos though)

**Comment by mattandrews** [comment]
Some sort of admin tool, maybe...

**Comment by mattandrews** [comment]
Okay with you @jamesoram?

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
