### PR TITLE
Remove scss-lint

### PR DESCRIPTION
**Pull request by davidrapson**
**Update**:

After doing some digging it turns out that this line `exclude: 'assets/stylesheets/components/*'` in our `scss-lint.yml` has meant that we've never actually been running `scss-lint` against the bulk of our styles. The majority of our styles live in `assets/stylesheets/components/`.

Given this, and given the number of people that actually touch our CSS (~2) we can say we're not getting any real benefit from `scss-lint` so we should remove it.

@mattandrews

### CODE REVIEW

**Comment by mattandrews** [comment]
:+1: 

Where was this change a few hours ago...

**Comment by davidrapson** [comment]
@mattandrews Might want to give this a double look as I've removed `scss-lint` completely now.

**Comment by mattandrews** [comment]
I'm happy with this. Especially since it wasn't running since last year...

**Comment by mattandrews** [comment]
:+1:

**Pull request merged**
