### PR TITLE
Replace About/Join/Homepage with single Homepage

### PR DESCRIPTION
**Pull request by davidrapson**
This PR is based off https://github.com/guardian/membership-frontend/pull/672 and makes the necessary changes to replace the About, Join, and old homepage with the new single homepage previously at https://membership.theguardian.com/join-challenger . Ignore the first commit which is from https://github.com/guardian/membership-frontend/pull/672

- Moves Join challenger template to the index
- Singed in users will now be redirected to the existing signed-in homepage, which now lives at `/welcome` as the templates are completely different. A new JS module has been added to handle this redirect.
- Join page has been removed, along with internal references to it
- About page has been removed
- The supporter landing page has been moved from `/about/supporter` to `/supporter` as `/about` no longer exists and is also a better match with the US page at `/us/supporter`
- Adds new Redirects controller to handle all moved pages

301 redirects have been added for all moved URLs:

- `/join-challenger` => `/`
- `/join` => `/`
- `/about` => `/`
- `/about/supporter`/ => `/supporter`

@rtyley @afiore

### CODE REVIEW

**Comment by afiore** [comment]
Looks like [model.NavTest](https://teamcity.gutools.co.uk/viewLog.html?buildId=713312&buildTypeId=Membership_Frontend&tab=buildLog#_focus=6372) is failing

**Comment by davidrapson** [comment]
@TesterSpike Looking at the functional tests, the only page that looks like it will cause issues is the removal of `JoinPage.scala`. Let me know if you want to pair on updating the functional tests. We might want to extend Join to work with the new homepage as this effectively replaces Join.

**Comment by davidrapson** [comment]
@TesterSpike I've updated the functional tests to merge the Join and Landing pages. However, as discussed there is an issue when signed in as a Member as we redirect existing members to `/welcome`. This redirect is done client-side and is async so it's confusing selenium.

Any thoughts on how to work around this and account for being sent to a different landing page when signed in as a Member?

Suites that are failing for `CoreTest` tag:

- `tests.MembershipBenefitTests`
- `tests.MembershipChangeTierTests`

**Comment by afiore** [comment]
:+1:

**Comment by TesterSpike** [comment]
:+1:

**Pull request merged**
