### PR TITLE
Simplify loader down to one-element

### PR DESCRIPTION
**Pull request by davidrapson**
This PR simplifies how the loader is constructed.

- Cleans up CSS conventions (use `is-` class rather than styling a `js-` class)
- Removes need for inline image / nested markup.
- Updates `processSubmit` to not be in utils (anything that's initialised in `main.js` should probably be in `modules`) and use loader helper to reduce code duplication

**Form loader**
loader mov

**Processing**
processing mov

### CODE REVIEW

**Comment by feedmypixel** [comment]
for the cancel membership the processing on the left feels a little far away - more a question for BenW bar that good tidy up = :+1:

**Comment by davidrapson** [comment]
@feedmypixel Yeah it does a little, might ask him and update in a separate PR if needed.

**Comment by davidrapson** [comment]
@jamesoram Mind giving this a once over, needs a check of forms to make sure loading spinners still display as expected.

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
