### PR TITLE
Bundles Landing Page - Pass Through INTCMP (And Other Tweaks)

### PR DESCRIPTION
**Pull request by Ap0c**
## Why are you doing this?

We want to keep track of how users are moving through the landing page flow, which we plan to do with INTCMP code. This passes INTCMP codes through from wherever the user arrives from (e.g. the epic), to the places they end up at (e.g. contributions, subs, etc.). If there is no INTCMP code, it sets a default: `gdnwb_copts_bundles_landing_default` (@jranks123, @desbo, @alexduf does this default work for you?).

It also includes some minor UI tweaks and fixes.

## Changes

- Tweak js to pass through INTCMP codes, or set a default in the situation this param is missing.
- Added minimum amount for contributions (fixes a bug where spaces were interpreted as `0` in other amount, because JavaScript is stupid).
- Changes the title of the page to 'Support the Guardian'.
- Minor tweak to other amount placeholder colour and added a `£` symbol.

### CODE REVIEW

**Comment by JustinPinner** [comment]
> because JavaScript is stupid

https://www.destroyallsoftware.com/talks/wat

**Comment by JustinPinner** [comment]
Looks reasonable. Second opinions welcome. 👍

**Comment by alexduf** [comment]
for the default campaign code 👍

**Comment by Ap0c** [comment]
Looks ok in PROD.

**Pull request merged**
