### PR TITLE
What's On: List view

### PR DESCRIPTION
**Pull request by davidrapson**
Branched off https://github.com/guardian/membership-frontend/pull/774. Commits start from `44dfc76`.

Adds a basic list/grid view toggle to the Events list page. Re-uses the existing (but previously hidden) calendar templates.

We are testing this as a generic **grid** vs **list** view for now. The intention is to launch this with an A/B test to split traffic between defaulting to the grid view vs. defaulting to the list view.

screen shot 2015-09-23 at 16 03 16

screen shot 2015-09-23 at 16 03 22

**Dev notes:**
- Separate listing actions into `WhatsOn` controller (and cleans out test what's on routes). The single `Event` controller was getting pretty huge to the function of this is to have one controller for detail pages (`Event`) and one for listings (`WhatsOn`)
- Creates common fragments for dates listings, DRY things up a bit

@chrisjowen @tudorraul

### CODE REVIEW

**Comment by davidrapson** [comment]
@dominickendrick Should be *slightly* easier to review now.

**Comment by dominickendrick** [comment]
:+1:

**Comment by davidrapson** [comment]
I've removed the actual toggle link so we can get this out but not link to it:

screen shot 2015-09-28 at 15 15 03

**Comment by tudorraul** [comment]
can you squash the latest 6 commits, it will make it easier to review the difference

**Comment by davidrapson** [comment]
Isn't that the same result as the files view? https://github.com/guardian/membership-frontend/pull/778/files

**Comment by davidrapson** [comment]
@tudorraul Any better?

**Pull request merged**
