### PR TITLE
Update patron page layout

### PR DESCRIPTION
**Pull request by davidrapson**
- Update patron page layout to match about page
- Remove homeslice styles!
- Cleanup dead images

**Large screen**
patrons - large

**Small screen**
patrons - small

### CODE REVIEW

**Comment by davidrapson** [comment]
Just for @wpf500 
screen shot 2015-02-04 at 14 28 07

**Comment by davidrapson** [comment]
@jamesoram Mind giving this a once over?

**Comment by jamesoram** [comment]
I found this on the ipad

screen shot 2015-02-04 at 15 38 01

**Comment by davidrapson** [comment]
Reduced the width of the titles on tablet so we don't cover up the centre of the image.

screen shot 2015-02-05 at 11 44 34

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
