### PR TITLE
Update Faq.scala

### PR DESCRIPTION
**Pull request by JuliaBellis**
Fixed a typo in a faq about the free tickets option for partners.

### CODE REVIEW

**Comment by JuliaBellis** [comment]
@rtyley

**Comment by rtyley** [comment]
:+1: :+1: :+1: :sparkles:

**Comment by JuliaBellis** [comment]
Fixed typo so tickets no longer means books. :boom:

**Comment by rtyley** [comment]
The TeamCity build server is overloaded :clock1130: - the build should be done in a few more minutes...

**Pull request merged**
