### PR TITLE
Add method of modelling responsive images in scala

### PR DESCRIPTION
**Pull request by davidrapson**
This PR adds a couple of new case classes to help model images. The main goal is to use these to reduce the duplication of image logic in `RichEvent` but as an initial test I have updated the homepage slideshow to use the new case class.

- Add `ResponsiveImageGroup` case class
- Add tests for `srcset` string generation
- Update homepage slideshow to use new `ResponsiveImageGroup` as a test case
- Bonus (basic) lazy-loading of images in the slideshow

Thanks to @jennysivapalan for the assistance on this one.

### CODE REVIEW

**Comment by jennysivapalan** [comment]
Looks good - I think the case classes will be more useful when we start pulling images for events / masterclasses etc.

**Comment by davidrapson** [comment]
@jennysivapalan Yeah definitely, probably going to have a look at that tomorrow as it looked fairly straightforward.

**Comment by davidrapson** [comment]
@jamesoram Mind giving this a once over? To confirm: Make sure that the carousel images on the homepage load OK.

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
