### PR TITLE
Update homepage video

### PR DESCRIPTION
**Pull request by joelochlann**
This PR updates the "What is membership?" video on the homepage from [this old video](https://youtu.be/z_IFkfuEuz0) to [this new video](https://youtu.be/oRowh6Nzt4c), along with its associated copy and placeholder image.

This also gave me an opportunity to remove references to an "alternate" (actually identical) version of this video which for some reason was only used in the `/patterns` page.

***Before***
crop2015-09-25-13h49m59s95

***After***
crop2015-09-25-13h50m21s65

@davidrapson

### CODE REVIEW

**Comment by davidrapson** [comment]
:+1: Nice cleanup. Let me know if you want to pair on deploying this, or if you've got enough to go on from yesterday then go ahead and hit merge.

**Comment by joelochlann** [comment]
Tested on PROD:
new-homepage-video

**Comment by davidrapson** [comment]
:gem: Congrats on your first deploy.

**Comment by joelochlann** [comment]
Cheers! Thanks for walking me through stuff yesterday

**Pull request merged**
