### PR TITLE
Fix alignment flash message

### PR DESCRIPTION
**Pull request by feedmypixel**
@marchibbins spotted the alignment of the feedback flash message was out of alignment when you were between the tablet and desktop breakpoints.
The flash message is displayed on pages with different layouts, functional and form layout pages.
- moved the layout out of the flash message fragment
- placed layout around the flash message fragment

## old (miss aligned)
old

## aligned correctly 
fixed

### CODE REVIEW

**Comment by jennysivapalan** [comment]
I think there might be a few more cases where the flash message is used - I added one for paid to paid upgrade.

**Comment by davidrapson** [comment]
:confused: Feels a little awkward to wrap these in a whole page section just for the flash message (not saying there should be any layout styles on the message component). Can these message live inside another container?

**Comment by feedmypixel** [comment]
> I think there might be a few more cases where the flash message is used - I added one for paid to paid upgrade.

merged and added

**Comment by davidrapson** [comment]
:+1:

**Pull request merged**
