### PR TITLE
Ammended the answer of one of the FAQ's questions.

### PR DESCRIPTION
**Pull request by svillafe**
## Why are you doing this?
We want to give more meaningful answer to our members.

## Changes
* Updated the `Faq.scala` with the last version of the answers.

## Screenshots

###Before
picture 129

### After
picture 128

### CODE REVIEW

**Comment by rupertbates** [comment]
👍 Nice, much better than the old wording!

**Comment by paulmichaelbrowne** [comment]
That looks great.

**Comment by svillafe** [comment]
It is working on **PROD**.

**Comment by svillafe** [comment]
[Amend contact us details](https://trello.com/c/eUo1hAL0/321-amend-contact-us-details)

**Pull request merged**
