### PR TITLE
UserDetails doesn't need constructor

### PR DESCRIPTION
**Pull request by davidrapson**
Bit of cleanup to `UserDetails`, doesn't need to be a constructor method (final module that was using this pattern).

@jennysivapalan

### CODE REVIEW

**Comment by davidrapson** [comment]
cc/ @rtyley as there is no more @mattandrews :(

**Comment by davidrapson** [comment]
@afiore Hey Andrea, would you mind giving this a look and giving a :+1: if it looks OK to you?

**Comment by afiore** [comment]
:+1: Looks fine to me. Just out of curiosity, why do you export `_.CLASS_NAMES` instead of `CLASS_NAMES` directly? Does `_` have a specific meaning in CommonJS?

**Comment by davidrapson** [comment]
@afiore Nope, it's a convention to signify that this is being exported just for tests, rather than a public API method.

**Comment by afiore** [comment]
Cool, thanks

**Comment by davidrapson** [comment]
Merged in latest changes a fixed some lint errors from new `eslint` setup.

screen shot 2015-06-18 at 12 07 41
---
screen shot 2015-06-18 at 12 07 55

**Pull request merged**
