### PR TITLE
Comment builder tool

### PR DESCRIPTION
**Pull request by feedmypixel**
A little tool as discussed with @mattandrews and @dominickendrick to help the events team with creating the comments needed for tagging events. This is currently sat on the /staff/event-overview page.

commentbuilder

Create comments for:
- Event Provider
- Event Image
- A "Not Sold though Eventbrite" event

Simply copy and paste the results into the Eventbrite html description.

I have tried to keep as much separate from the main app as possible, hence the split of the JS in the same manner as the CSS has been done. This means this can be easily extracted from the main app if needed.

### CODE REVIEW

**Comment by mattandrews** [comment]
Just made a quick addon:

screen shot 2015-02-23 at 17 40 24

This allows Masterclass tagging too.

**Comment by mattandrews** [comment]
(eg. `<!-- tags:Journalism,Business -->`)

**Comment by feedmypixel** [comment]
> Just made a quick addon:

:metal:

**Comment by mattandrews** [comment]
:+1:

**Comment by feedmypixel** [comment]
:+1:

**Comment by feedmypixel** [comment]
@mattandrews 
- have changed to use require as it feels nicer and gives us all that require and our other modules bring,
- added it to masterclasses event overview also

**Comment by davidrapson** [comment]
:+1: LGTM. I'd be keen to extract this from the rest of the app though if this gets more complex, but guessing this is probably going to be replaced anyway.

**Comment by mattandrews** [comment]
@davidrapson yep, this is just a plaster to temporarily cover the gaping wound of the HTML comments approach. We want to work today on improving it as a tool.

**Comment by davidrapson** [comment]
Excellent, I thought as much.

**Comment by feedmypixel** [comment]
> I'd be keen to extract this from the rest of the app though if this gets more complex,

sure, the tools styles and js are separate so will be easy to pull out to another app if needed

**Pull request merged**
