### PR TITLE
Serve complimentary tickets to all users

### PR DESCRIPTION
**Pull request by afiore**
@davidrapson

### CODE REVIEW

**Comment by davidrapson** [comment]
:+1:

**Comment by afiore** [comment]
@rtyley mind having a quick look at this?

**Comment by rtyley** [comment]
Looks good, though we should probably also remove the `Config.stageDev` property altogether.

**Comment by afiore** [comment]
Deployed successfully on prod (still looks like the event in this screenshot has been slightly misconfigured on the Eventbrite side).
screen shot 2015-09-08 at 14 36 26

**Pull request merged**
