### PR TITLE
Add password authentication on paid to paid upgrades

### PR DESCRIPTION
**Pull request by jennysivapalan**
On paid to paid upgrades we need the user to re-enter their password.

I'm just waiting on copy from @davidmcdowell but otherwise this is good to be reviewed.

@jamesoram Let me know if you want to run through testing this? Locally I've been testing this by signing up as a partner and then upgrade to patron.

### CODE REVIEW

**Comment by jamesoram** [comment]
:+1:

**Comment by jennysivapalan** [comment]
Done!

**Comment by rtyley** [comment]
:+1:

**Comment by jennysivapalan** [comment]
Tested on PROD  the partner -> patron and friend -> partner route and all works as expected.

**Pull request merged**
