### PR TITLE
Display the ticket sale times if any of them are not midnight. 

### PR DESCRIPTION
**Pull request by AWare**
https://trello.com/c/AX2t2vRV/86-show-time-on-the-ticket-availability-panel-on-the-event-page

[selfie-0](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Comment by AWare** [comment]
image
=>
image

**Comment by tomverran** [comment]
:+1:

**Comment by rtyley** [comment]
I'm fine with this, but I'd like to know which stakeholder said to go ahead with it? We've already removed times once.

**Comment by AWare** [comment]
This came from Natalie and Sophie in events as showing just the date for non midnight sale starts was poor ux, and members were complaining about tickets not being available.

**Pull request merged**
