### PR TITLE
Use sitemap to raise priority of supporter landing pages in search

### PR DESCRIPTION
**Pull request by rtyley**
Initially a query came from Nick M Miller & Michael Campbell, asking if we could redirect https://membership.theguardian.com/ to https://membership.theguardian.com/us/supporter for US users. Apparently some US users find https://membership.theguardian.com/ through google, but there's a fear that the UK-specific pricing on that page immediately puts them off. In any case, the homepage is not tuned to US users.

I'm not too sure about auto-redirecting, but I think that by adding information to our sitemap, we will be able to improve the ranking priority of the supporter pages over the homepage, which Charles Minty has confirmed would be desirable for UK users too. Through `alternate` `hreflang` settings, we can hopefully get google US to prioritise the US supporter page, and google UK to prioritise the UK supporter page.

Sitemap documentation consulted...
---

Regarding the alternate `hreflang`:
* "Use a sitemap to indicate alternate language pages"
  https://support.google.com/webmasters/answer/2620865?hl=en
* "Use hreflang for language and regional URLs"
  https://support.google.com/webmasters/answer/189077?hl=en

Regarding `priority`:
* https://webmasters.googleblog.com/2008/01/sitemaps-faqs.html

Generated sitemap.xml
----

http://localhost:9100/sitemap.xml currently returns:

```
<urlset xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>http://localhost:9100/uk/supporter</loc>
<priority>1.0</priority>
<xhtml:link rel="alternate" hreflang="en-gb" href="http://localhost:9100/uk/supporter" />
<xhtml:link @relrel="alternate" hreflang="en-us" href="http://localhost:9100/us/supporter" />
<xhtml:link rel="alternate" hreflang="en-ca" href="http://localhost:9100/ca/supporter" />
<xhtml:link rel="alternate" hreflang="en-au" href="http://localhost:9100/au/supporter" />
</url>
<url>
<loc>http://localhost:9100/us/supporter</loc>
<priority>1.0</priority>
<xhtml:link rel="alternate" hreflang="en-gb" href="http://localhost:9100/uk/supporter" />
<xhtml:link rel="alternate" hreflang="en-us" href="http://localhost:9100/us/supporter" />
<xhtml:link rel="alternate" hreflang="en-ca" href="http://localhost:9100/ca/supporter" />
<xhtml:link rel="alternate" hreflang="en-au" href="http://localhost:9100/au/supporter" />
</url>
<url>
<loc>http://localhost:9100/ca/supporter</loc>
<priority>1.0</priority>
<xhtml:link rel="alternate" hreflang="en-gb" href="http://localhost:9100/uk/supporter" />
<xhtml:link rel="alternate" hreflang="en-us" href="http://localhost:9100/us/supporter" />
<xhtml:link rel="alternate" hreflang="en-ca" href="http://localhost:9100/ca/supporter" />
<xhtml:link rel="alternate" hreflang="en-au" href="http://localhost:9100/au/supporter" />
</url>
<url>
<loc>http://localhost:9100/au/supporter</loc>
<priority>1.0</priority>
<xhtml:link rel="alternate" hreflang="en-gb" href="http://localhost:9100/uk/supporter" />
<xhtml:link rel="alternate" hreflang="en-us" href="http://localhost:9100/us/supporter" />
<xhtml:link rel="alternate" hreflang="en-ca" href="http://localhost:9100/ca/supporter" />
<xhtml:link rel="alternate" hreflang="en-au" href="http://localhost:9100/au/supporter" />
</url>
<url>
<loc>http://localhost:9100/</loc>
<priority>0.8</priority>
</url>
</urlset>
```

cc @paulbrown1982

### CODE REVIEW

**Comment by paulbrown1982** [comment]
👍 nice one

**Comment by rtyley** [comment]
Sitemap is visible on PROD, but annoyingly is linking to HTTP, not HTTPS urls

https://membership.theguardian.com/sitemap.xml

**Comment by rtyley** [comment]
I've just submitted the sitemap:

https://www.google.com/webmasters/tools/sitemap-list?hl=en&authuser=0&siteUrl=https://membership.theguardian.com/#MAIN_TAB=0&CARD_TAB=-1
image

(note that they'res not indexed yet, and are marked pending)

Currently, google search results are unchanged:

Google.co.uk
image

Google.com (ie US)
image

**Comment by rtyley** [comment]
See also [this search](https://www.google.ca/#q=guardian+membership+supporter) from Google Canada:

image

...US supporter is appearing above CA supporter.

**Pull request merged**
