### PR TITLE
Upgrade Stripe for PCI DSS

### PR DESCRIPTION
**Pull request by davidrapson**
This upgrade ensures we are compliant with the new PCI Data Security Standards (PCI DSS 3.0)
**See**: [https://support.stripe.com/questions/what-about-pci-dss-3-0]()

Stripe now explicitly disallows loading `stripe.js` from your own domain, resulting in the following console warning:

```
"It looks like Stripe.js is not being loaded from https://js.stripe.com.
Stripe does not support serving Stripe.js from your own domain."
```

This means we now aync load `stripe.js` before initialising `form#payment.init()` and call methods directly on the `Stripe` global.

**Updates**
- Removes version of `stripe.js` stored in `lib/`
- Updates stripe to new version, `https://js.stripe.com/v2/stripe-dss3.js`

@rtyley @dominickendrick @TesterSpike

### CODE REVIEW

**Comment by mattandrews** [comment]
Code looks good but yeah, let's test this heavily.
:+1:

**Comment by davidrapson** [comment]
@TesterSpike Let me know once you're happy with this

**Comment by davidrapson** [comment]
@TesterSpike Got the approval from Jonathan, you happy to +1 this?

**Comment by TesterSpike** [comment]
:+1:

**Comment by davidrapson** [comment]
Confirmed on PROD

screen shot 2015-05-20 at 14 47 11

**Pull request merged**
