### PR TITLE
Remove gifting placeholder route

### PR DESCRIPTION
**Pull request by davidrapson**
This PR removes `/gifting`. Looking at analytics it has had a grand-total of 6 page-views since launch.

screen shot 2015-08-11 at 11 29 28

@afiore

### CODE REVIEW

**Comment by afiore** [comment]
Are there any internal links pointing to it?

**Comment by davidrapson** [comment]
@afiore Nope, no internal links that I know of, but w/1 visitor in the last 6 months I think It's safe to remove.

**Comment by davidrapson** [comment]
@afiore This OK to be merged in?

**Comment by afiore** [comment]
:+1:

**Pull request merged**
