### PR TITLE
Update event discount copy to explain booking fees

### PR DESCRIPTION
**Pull request by tomverran**
#### discounted tier

was
image

now
image

#### without discounted tier

was
image

now
image

### CODE REVIEW

**Comment by chrisjowen** [comment]
One really small thing one slightly bigger issue. Firstly can you indent priceInfoEvent.scala.html its really hard to see that the discountTicketing came from the result of the fold. 

Secondly there have been discussions in general about only passing to the view what the view need, i.e. some kind of view model. I appreciate that the prefer that the RichEvent that we pass down is a mixture of a ViewModel and for lack of better word a business model. But passing the Config object to the view too seems odd. I know that Tom and Andrea did some work on separating these things in other places, I wondered if this would be a difficult thing to do here too.

**Comment by tomverran** [comment]
So I do agree passing domain objects into the view is pretty bad, I've removed the dependency on the config at least but splitting out the view logic from the Eventbrite response seems like a big job

**Comment by chrisjowen** [comment]
I appreciate that the size of the change probably exceeds this PR, so :+1

**Comment by tomverran** [comment]
image

image

**Pull request merged**
