### PR TITLE
Constrain terms in events header

### PR DESCRIPTION
**Pull request by feedmypixel**
Add constrained modifier for terms found in events header

screen shot 2015-03-24 at 12 45 21

### CODE REVIEW

**Comment by davidrapson** [comment]
Sorry :-1: 

Can we try and remove the terms-info class completely? So put styles for the header in a new `. event-ticket__terms` container and `.event-info__terms` for the sidebar?

**Comment by davidrapson** [comment]
I rejigged this so that we don't need the broad `terms-info` class any more and we style them as specific parts of their respective components.

**Comment by davidrapson** [comment]
Mind taking a look @mattandrews as I can't really thumbs up this now.

**Comment by mattandrews** [comment]
Looks fine to me although I'm not 100% clear on what the overall goal was here...

**Comment by mattandrews** [comment]
:+1:

**Comment by davidrapson** [comment]
@mattandrews The header and the sidebar were sharing a class for styling, even though there was no shared styling between the two. So rather than doing lots of overriding, this just splits the styles out.

**Comment by feedmypixel** [comment]
:+1:

**Pull request merged**
