### PR TITLE
Remove videoWhatIsGuardianMembership from Config

### PR DESCRIPTION
**Pull request by davidrapson**
Doesn't feel like this needs to be config

### CODE REVIEW

**Comment by feedmypixel** [comment]
:+1:

**Comment by davidrapson** [comment]
@jamesoram Mind giving this one a quick check, just confirm that the video still displays on the about page.

**Comment by jamesoram** [comment]
:+1:

**Comment by jennysivapalan** [comment]
I think given it's in two places it should be defined once and used in both, the config seems fine to me?

**Comment by jamesoram** [comment]
yeah I asked that but apparently the video does not have to be the same in both places

**Comment by davidrapson** [comment]
I guess my thinking was it's not environment specific so doesn't hugely need to be in application.conf, and the second usage is for the pattern library an so could (and probably should) be any video.

**Comment by jennysivapalan** [comment]
Okay. Anything defined in application.conf can be used for any environment but you can add specific environment overrides in files such as dev.conf or prod.conf

**Comment by davidrapson** [comment]
Cheers. I'm happy to close this as it sounds like it doesn't hurt to have it in the config.

**Pull request closed without merging**
