### PR TITLE
Change metadata discover to local

### PR DESCRIPTION
**Pull request by feedmypixel**
- change logo from `Discover` to `Local`
- change meta data from `Discover` to `Local`
- change `Discover` to `Local` references in code, routes and api key

*note the DEV and PROD keys need updating before this goes out*

screen shot 2015-03-24 at 16 23 26

### CODE REVIEW

**Comment by davidrapson** [comment]
:+1: Looks good for the client-side stuff…although Local is an unfortunately confusing name in the code.

**Comment by feedmypixel** [comment]
@jamesoram can you have a good look over

**Comment by jennysivapalan** [comment]
:+1: :arrow_backward:

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
