### PR TITLE
Set the correct value for elements in the 'State' dropdown

### PR DESCRIPTION
**Pull request by rupertbates**
## Why are you doing this?
To fix a bug which is preventing US and Canadian users checking out

### CODE REVIEW

**Comment by johnduffell** [comment]
👍 🚀 quick work, thanks!

**Comment by Ap0c** [comment]
All fixed running locally, nice! 🐟

**Comment by svillafe** [comment]
Tested in UK, CA and US and it is working locally.

**Comment by johnduffell** [comment]
also looks good in prod 😀

**Pull request merged**
