### PR TITLE
Use new Tier case objects

### PR DESCRIPTION
**Pull request by wpf500**
Upgrade `membership-common` to 0.50 to make use of the new `Tier` case objects.

Most of this change involves changing `Tier.Value` or `Tier.Tier` to just `Tier`.

Tiers now contain some properties, one of which is `slug`, which can be used in place of `Tier.toString.toLowerCase`, it is also what we use for routing.

### CODE REVIEW

**Comment by wpf500** [comment]
cc @rtyley @jennysivapalan especially for code review

**Comment by wpf500** [comment]
@jamesoram this contains quite a few changes, some of which affect the join flows. Do you want to do anything to check you are happy with the changes?

**Comment by jennysivapalan** [comment]
Nice :+1: :runner:

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
