### PR TITLE
Subscriber offer

### PR DESCRIPTION
**Pull request by jennysivapalan**
The final part that has been extracted from #449 is provide subscriber offer to Partners. Note this is also now behind OAuth meaning we can test and release this early but not make it available to the public until the business is ready.

We have already put into production all the work to handle free period offers, the impact on changes to tiers and the validation checks for subscriber offer. None if is used though until now.

@davidrapson I implemented your suggestions for https://github.com/guardian/membership-frontend/pull/449#discussion_r28316830 and https://github.com/guardian/membership-frontend/pull/449#discussion_r28316733 in this PR.

@jamesoram This will need a re-test with Jason. You'll need to hit test-users endpoint to ensure the OAuth is dropped into the cookie but then you should see the subscriber fields.

~~I think we still need to change the rate plan in Zuora production before we can go live with this.~~

### CODE REVIEW

**Comment by jamesoram** [comment]
:+1:

**Comment by davidrapson** [comment]
:+1: to the client-side work.

**Comment by jennysivapalan** [comment]
RELAX @prout-bot it's on Prod AND it works :boom: 
cc @rtyley

**Comment by rtyley** [comment]
I hit https://prout-bot.herokuapp.com/api/update/guardian/membership-frontend manually, which will let Prout catch up with things - once something's overdue, it doesn't keep on polling- but it should have got a kick from Riff Raff, hmm...

**Comment by jennysivapalan** [comment]
ahh good to know. Also exciting that this is done! :fireworks:

**Comment by rtyley** [comment]
:bomb:  :boom:  :sparkles: !

**Pull request merged**
