### PR TITLE
[Do Not Merge] Added an updated version of cloud formation's yaml

### PR DESCRIPTION
**Pull request by svillafe**
# Do not merge
Before merging this PR we need to wait for the acquisition team to remove snowplow from membership. 
See related PR: https://github.com/guardian/membership-frontend/pull/1744

## Why are you doing this?
To be sure that all of our outgoing connections are secured.

### CODE REVIEW

**Comment by svillafe** [comment]
Acquisition team came up with PR to remove snowplow: https://github.com/guardian/membership-frontend/pull/1757 they are waiting for the confirmation that they can do it.

**Comment by johnduffell** [comment]
you have to merge or close before you move! @svillafe

**Comment by svillafe** [comment]
Thank you for flagging this up @johnduffell, I will catch up with @davidfurey if is necessary to merge this PR or we can close it.

**Comment by svillafe** [comment]
After going through this with @davidfurey, we decided to close it.

**Pull request closed without merging**
