### PR TITLE
Rolling back webpack 2

### PR DESCRIPTION
**Pull request by svillafe**
## Why are you doing this?
Webpack 2 is not running in IE11, therefore we are rolling it back.

## Update to webpack 2 PR:
https://github.com/guardian/membership-frontend/pull/1516/files
## Tested in:
* IE
* Firefox
* Chrome
* Safari

### CODE REVIEW

**Comment by rupertbates** [comment]
After discussion, this seems like a good fix until we work out what's going on. 👍

**Comment by Ap0c** [comment]
Seems to work ok 👍

**Comment by paulbrown1982** [comment]
👍

**Comment by svillafe** [comment]
acceptance tests running locally

**Comment by svillafe** [comment]
It took 14min teamcity to compile it.

**Comment by svillafe** [comment]
The checkout flow is working on IE.

**Pull request merged**
