### PR TITLE
Store all the current grid urls to Event Image in a map. 

### PR DESCRIPTION
**Pull request by jennysivapalan**
This should reduce how often we make a call to the Grid.

### CODE REVIEW

**Comment by wpf500** [comment]
:+1:

**Comment by jennysivapalan** [comment]
:pushpin:

**Comment by mattandrews** [comment]
Does Will suck?           
                        +                  
                        |                  
                        |                  
                        |                  
               +--------+---------+        
               |                  |        
               |                  |        
               |                  |        
               |                  |        
               |                  |        
      +--------+-----+     +------+-------+
      |     Yes      |     |    Yes       |
      |              |     |              |
      +--------------+     +--------------+

**Pull request merged**
