### PR TITLE
Disable analytics in DEV mode

### PR DESCRIPTION
**Pull request by davidrapson**
Just thought I'd check if there there a reason we have analytics enabled for all stages?

### CODE REVIEW

**Comment by mattandrews** [comment]
We load a dev account for Google Analytics (useful for testing), although Omniture/Ophan are still loaded for DEV (and presumably disregard data that doesn't match the domain whitelist). @rtyley?

**Comment by tackley** [comment]
Yup - ophan will definitely exclude by default all traffic inside a guardian office. Personally I'd recommend you keep it enabled in DEV stages as (I'm biased) analytics is probably the most important function not to break. Therefore having it working (/breaking) in DEV and pre-production I'd view as very important.

In the ophan dashboard, you can view inside-the-guardian traffic by adding country=GNM to any url.

**Comment by mattandrews** [comment]
Ha, the independent republic of GNM...

Also, I swear @tackley has a batsignal-like alert every time a comment mentions Ophan :grinning:

**Comment by davidrapson** [comment]
@tackley Thanks Graham! Totally agree, I was sure there would be a good reason.

**Comment by tackley** [comment]
@mattandrews actually yes - all my github notifications skip my inbox **unless** the mention ophan :)  That then turns into a call to strip down to my pants and put my cape on.

**Pull request closed without merging**
