### PR TITLE
Improve UX of video player

### PR DESCRIPTION
**Pull request by davidrapson**
This PR adds an overlay effect to videos. Uses the YouTube API to start playback of the video when the user clicks on the overlay.

video-2 mov

- Adds new `Video` model and models individual videos in the config
- Add `videoOverlay` component, YT API is lazyloaded only when needed
- Extract out new `videoPlayer` fragment and adds to pattern library

**Caveats**

- We have to load the YouTube iFrame API to trigger video playback
- iOS does not like us triggering playback, so there's a bit of nasty UA detection in here to only start playback on non iOS devices.

This is a medium-term solution until we can use the Guardian player over HTTPS in a couple of months. Are the trade-offs with this approach worth it?

@mattandrews

### CODE REVIEW

**Comment by mattandrews** [comment]
Looks nice. :+1:

**Comment by davidrapson** [comment]
@jamesoram Look OK to you?

**Comment by jamesoram** [comment]
:+1:

**Comment by davidrapson** [comment]
Just waiting for a different placeholder image for the Supporter video from Ben W, then this can go out.

**Comment by davidrapson** [comment]
Confirmed on PROD

screen shot 2015-04-13 at 12 24 30

**Pull request merged**
