### PR TITLE
Paid to paid promotion support

### PR DESCRIPTION
**Pull request by tomverran**
This adds a promoCode form element you can fill in that will apply promotions and update the payment preview.

Better error checking and pre population are still in progress

### CODE REVIEW

**Comment by paulbrown1982** [comment]
Looks and works very nicely.

Two bugs spotted in testing: 
1) Absence of autocomplete=off on the password field causes the browser to display the popup to remember the password (using the promocode field as the username)

picture 66

2) Upon putting in an invalid password and clicking the CTA, the page refreshes with the red:
That password does not match our records. Please try again.  and the promocode is not filled in.

3) There is no tracking promo code added. I've added this as a bullet to: https://trello.com/c/3sMxyCLI/485-tracking-codes-for-membership

4) For some reason my sessioned TRACK01 cookie is what got stored in Zuora.

5) The summary page showed Amount paid today £0

**Comment by tomverran** [comment]
So out of the issues raised above the one I haven't fixed is Firefox saving the password and promo code - the password field does have ```autocomplete=off``` but Firefox ignores it

http://stackoverflow.com/questions/25418059/disabling-password-auto-complete-in-firefox

**Comment by paulbrown1982** [comment]
👍

**Comment by tomverran** [comment]
Can go live when https://github.com/guardian/membership-common/pull/222 is released

**Pull request merged**
