### PR TITLE
Remove unused image widths from Config

### PR DESCRIPTION
**Pull request by davidrapson**
Spotted whilst working on PR https://github.com/guardian/membership-frontend/pull/417, these config items have ben unused since the recent responsive image/srcset work went out.

### CODE REVIEW

**Comment by mattandrews** [comment]
:+1: 

(build failed though?)

**Comment by davidrapson** [comment]
Missed a spot… hopefully that's sorted it

**Comment by davidrapson** [comment]
https://status.github.com/messages

**Comment by davidrapson** [comment]
Github seems to be recovering a bit from the DDoS so this has finally gone out https://status.github.com/messages

**Pull request merged**
