### PR TITLE
Form tidy-up

### PR DESCRIPTION
**Pull request by davidrapson**
A few bits of clean up around forms:

- Use single fragment for form security note. Inline icon
- Tweak how form note right is aligned (fix double float issue)
- Use copy styles for signedInAs (adds underline to link)
- Move card sprite into form, consistent w/ other images

screen shot 2015-02-25 at 11 18 02

### CODE REVIEW

**Comment by feedmypixel** [comment]
:+1:

**Comment by davidrapson** [comment]
@jamesoram Mind giving the forms a once over to make sure everything still looks OK?

**Comment by davidrapson** [comment]
@jamesoram Fixed the alignment issue for the card labels on small screens, was that all you spotted?

screen shot 2015-03-03 at 11 05 51

**Comment by mattandrews** [comment]
:+1:

**Comment by davidrapson** [comment]
Note: @jamesoram to review (as he spotted the initial layout issue) before this goes out.

**Comment by jamesoram** [comment]
:+1:

**Comment by davidrapson** [comment]
merging :rocket:

**Pull request merged**
