### PR TITLE
uri has been removed from the Grid API. 

### PR DESCRIPTION
**Pull request by jennysivapalan**
We need to remove reference to this as it breaks loading of events.

### CODE REVIEW

**Comment by rtyley** [comment]
:+1:

cc @theefer  & https://github.com/guardian/media-service

**Comment by theefer** [comment]
:+1:

Sorry :cry:

**Comment by jennysivapalan** [comment]
We don't actually use it so was an easy fix.

**Comment by theefer** [comment]
Cool.

FYI I'm working on a [Scala library](https://github.com/guardian/media-service/blob/master/common-lib/src/main/scala/com/gu/mediaservice/lib/argo/model/EntityReponse.scala) to help interact with [argo](https://github.com/argo-rest/spec) hypermedia APIs (argo is the media-type we use on Grid, Composer, Tag API & others).

I've just released it to PROD (in fact that's the PR that removed the `uri` and broke your integration :smile:) and will be doing more work with it until I'm happy enough to break it into a separate library, which others could then start using if they wish.

**Pull request merged**
