### PR TITLE
Fix Staff tier - I think this is all we need to do!

### PR DESCRIPTION
**Pull request by paulbrown1982**
cc @rtyley @svillafe @Ap0c @johnduffell

### CODE REVIEW

**Comment by Ap0c** [comment]
Excellent fix!

One thing that still seems odd: when you first set up a staff membership you initially get an email saying thanks for joining as a Partner, and then immediately get a second email saying your tier has been changed to Friend... This seems to explain the Friend part, but is there a reason it would assign a Partner tier first?

**Comment by paulbrown1982** [comment]
def joinStaff = AuthenticatedNonMemberAction.async { implicit request =>
    staffJoinForm.bindFromRequest.fold(redirectToUnsupportedBrowserInfo,
        makeMember(Tier.partner, Redirect(routes.Joiner.thankyouStaff())) )
  }

FWICT It's always been set way. Staff get Partner benefits - and I think this setting makes Zuora set up usable benefits on the staff sub - i.e. 6 free event tickets.

**Comment by johnduffell** [comment]
👍 good spot! not sure why it was left like that, hopefully there wasn't a good reason.

**Comment by svillafe** [comment]
It is working picture 12

**Comment by paulbrown1982** [comment]
From Zuora: picture 209

**Pull request merged**
