### PR TITLE
Reestablish Webpack 2 and Fix Promise Bug With Polyfill Service

### PR DESCRIPTION
**Pull request by Ap0c**
## Why are you doing this?

We previously had to revert webpack 2 in #1536 because it broke the site in IE due to its dependency on `Promise`. This PR reinstates the webpack 2 upgrade, and polyfills `Promise` (and `fetch`) using the polyfill service implemented by @janua. Takes inspiration from a similar change in [subs frontend](https://github.com/guardian/subscriptions-frontend/pull/794) implemented by @AWare.

Original update to webpack 2 PR: https://github.com/guardian/membership-frontend/pull/1516

[**Trello Card**](https://trello.com/c/18uJRoip/375-fix-broken-checkout-on-ie11)

## Changes

- Revert #1536.
- Add polyfills for `Promise` and `fetch` to `javaScriptFirstSteps` using polyfill service.
- Removed `whatwg-fetch` as dep.

cc @JustinPinner to bypass his email filters.

### CODE REVIEW

**Comment by AWare** [comment]
I'd just pull in the whole of default, it should lessen IE compatibility worries.

**Comment by Ap0c** [comment]
> I'd just pull in the whole of default, it should lessen IE compatibility worries.

I did this originally, it broke stuff in IE.

You're right that that's a nice solution though, I think we could go through and replace our other polyfills using the default in a separate PR.

**Comment by Ap0c** [comment]
@JustinPinner the first commit, ffe1546, mostly just reapplies the stuff from #1516. The new content in this PR is tbh fairly minimal 🐰.

**Comment by JustinPinner** [comment]
Based on the discussion I just had with @Ap0c: 👍 (We can also keep a close eye on it post deployment)

**Comment by svillafe** [comment]
Acceptance tests are running locally ✅

**Comment by svillafe** [comment]
## Stripe Checkout Test:
# IE10 (Windows 7): 🔴  
**FAILED** **Error:**SEC7118: XMLHttpRequest for https://api.stripe.com/v1/tokens required Cross Origin Resource Sharing (CORS). 
index-178d6d6af7182f292611bb0bf6abb95e.html
#IE11 (Windows 7): 🔴  Same error as above

**Comment by Ap0c** [comment]
> FAILED **Error:**SEC7118: XMLHttpRequest for https://api.stripe.com/v1/tokens required Cross Origin Resource Sharing (CORS).
> index-178d6d6af7182f292611bb0bf6abb95e.html

Are you sure that's the error? I've just run through it and that just looks like a console info message for me. Also I was able to sign up fine in IE10 on Windows 8.

**Comment by svillafe** [comment]
@Ap0c I have just re-run the checkout flow in IE10 on windows 7 and it is working. I have updated the table above.

**Comment by svillafe** [comment]
## PROD TEST
| Browser | Status | Stripe | Paypal
|---------|--------|--------|--------|
|    **IE10 (Windows 7)**      |      |
| **IE11 (Windows 7)**        |       |
|    **IE10 (Windows 8)**     |      |
|    **Chrome Version 56.0.2924.87 (64-bit) for Mac**||
|    **🦊 Firefox for Mac** |  |
|    **Safari for Mac** |  |

**Comment by Ap0c** [comment]
We've run through the flow several times, everything seems to be working ok.

**Pull request merged**
