### PR TITLE
[Do not merge] Show members area content on joiner thank you page

### PR DESCRIPTION
**Pull request by davidrapson**
Second attempt at this. This PR shows an article snapshot on the joiner page if the user joined via members area content on gu.com.

**Content**
joiner - content

**Event**
joiner - event

**Default**
joiner - default

It also refactors the matching on the event thank you page to take a new `Destination` option which can be one of the following values:

a. `None` => Basic joiner flow (e.g., from pricing page)
b. `EventDestination` => User joined via an event
c `ContentDestination` => User joined via members area content on gu.com

Following the error yesterday I've added a check to ensure that calls to CAPI only happen for gu.com content and added a `recover` block to handle any CAPI errors.

// @rtyley

### CODE REVIEW

**Comment by davidrapson** [comment]
@jamesoram I'd appreciate your thoughts on how best to test this, whether the behaviour can be covered by integration tests or if we should push it into unit tests.

**Comment by jamesoram** [comment]
yeah this looks like something that should be tested using mocks as adding functional tests for this will be slow and unstable

**Comment by davidrapson** [comment]
@jamesoram It's worth us having a quick chat about best approach for this then.

**Comment by jennysivapalan** [comment]
@davidrapson I've added the tests to this PR and fixed merge conflicts with master (though can you check I made the changes correctly on `thankyou.scala`).

**Comment by davidrapson** [comment]
Closing in favour of https://github.com/guardian/membership-frontend/pull/497

**Pull request closed without merging**
