### PR TITLE
add browse our events back onto the signed out homepage

### PR DESCRIPTION
**Pull request by feedmypixel**

### CODE REVIEW

**Comment by davidrapson** [comment]
@feedmypixel Do we want this? Did some digging into analytics with David M and there has been little practical impact since removing this. Patron feels more important than events (given that the panel didn't increase traffic to /events in a meaningful way)

**Comment by feedmypixel** [comment]
Lets have a natter with Jeff when he is back not sure on the reason for this but is  [#687](https://jira.gutools.co.uk/browse/MEM-687) in Jira

**Comment by feedmypixel** [comment]
Confirmed with Jeff this is a request from Charles

**Comment by davidrapson** [comment]
:+1:

**Pull request merged**
