### PR TITLE
Remove Imager.js

### PR DESCRIPTION
**Pull request by davidrapson**
This PR removes Imager.js as a dependency by updating remaining images to use native responsive images (only `promoPrimary`).

- Remove Imager.js :no_entry_sign: 
- All promo images now using `ResponsiveImage` and modelled in controller

### CODE REVIEW

**Comment by feedmypixel** [comment]
:+1: good stuff
:wave::wave: Imager

**Comment by davidrapson** [comment]
@jamesoram Mind giving this a once over by confirming that all images display on About, Patron and Supporter page.

**Comment by jamesoram** [comment]
:+1:

**Comment by davidrapson** [comment]
Confirmed on PROD. Now 100% `srcset`!

**Pull request merged**
