### PR TITLE
So Long, and Thanks for All the Fish

### PR DESCRIPTION
**Pull request by feedmypixel**

### CODE REVIEW

**Comment by davidrapson** [comment]
rilzzri

**Comment by mattandrews** [comment]
giphy

**Comment by mattandrews** [comment]
Note that I'm not calling you a traitor to the Rebel Alliance.

**Comment by mattandrews** [comment]
Nor am I saying you're Billy Dee Williams.

**Comment by mattandrews** [comment]
██████╗  ██████╗  ██████╗ ██████╗ ██████╗ ██╗   ██╗███████╗
    ██╔════╝ ██╔═══██╗██╔═══██╗██╔══██╗██╔══██╗╚██╗ ██╔╝██╔════╝
    ██║  ███╗██║   ██║██║   ██║██║  ██║██████╔╝ ╚████╔╝ █████╗  
    ██║   ██║██║   ██║██║   ██║██║  ██║██╔══██╗  ╚██╔╝  ██╔══╝  
    ╚██████╔╝╚██████╔╝╚██████╔╝██████╔╝██████╔╝   ██║   ███████╗
     ╚═════╝  ╚═════╝  ╚═════╝ ╚═════╝ ╚═════╝    ╚═╝   ╚══════╝
                                                                
    ██████╗ ███████╗███╗   ██╗██╗                               
    ██╔══██╗██╔════╝████╗  ██║██║                               
    ██████╔╝█████╗  ██╔██╗ ██║██║                               
    ██╔══██╗██╔══╝  ██║╚██╗██║╚═╝                               
    ██████╔╝███████╗██║ ╚████║██╗                               
    ╚═════╝ ╚══════╝╚═╝  ╚═══╝╚═╝

**Pull request merged**
