### PR TITLE
Move shared links & videos out of application.conf

### PR DESCRIPTION
**Pull request by davidrapson**
After discussion with @rtyley this PR moves static links and video URLs out of `application.conf` and converts them to constants in new standalone config objects. This approach feels cleaner as these links don't change between environments, and now only one file needs to be updated to add new links instead of two.

Planning on doing the same with the email addresses, but will do that in another PR.

### CODE REVIEW

**Comment by rtyley** [comment]
:+1:

`Links` is a bit generic, but I think it'll do for now, until we get so many links that some kind of sub-grouping becomes obvious.

**Comment by davidrapson** [comment]
> Links is a bit generic, but I think it'll do for now, until we get so many links that some kind of sub-grouping becomes obvious.

100% agreed.

Look OK to you @jamesoram

**Comment by jamesoram** [comment]
:+1:

**Comment by mattandrews** [comment]
Looks sensible to me :+1:

**Comment by davidrapson** [comment]
https://status.github.com/messages

**Pull request merged**
