### PR TITLE
Remove old data-uri icons

### PR DESCRIPTION
**Pull request by davidrapson**
This PR removes the remaining old data-uri'd SVG icons so that all icons now use inline SVGs.

- Removes remaining non-inline SVGs
- Updates `action-proceed` (the small icon in the corner) to be an `icon-holder` (like the back to the top icon).
- Manually inline `arrow-left` as the main `.action` class is the last place data-uri'd icons are used, this need a larger set of changes to remove so leaving for another PR
- Removes some dead `.action` styles
- Removed `svgencode.py`, sorry @wpf500 

screen shot 2015-03-27 at 10 47 07

Pre-gzip CSS size also gets a decent decrease with this change.

**Before**
before

**After**
after

:skull:

### CODE REVIEW

**Comment by wpf500** [comment]
This is a sad day

**Comment by davidrapson** [comment]
cryingbear

**Comment by mattandrews** [comment]
I'd recommend using @rtyley's [BFG](https://rtyley.github.io/bfg-repo-cleaner/) to remove all traces of @wpf500's `svgencode.py`. Ideally it should appear as though it had never been. All traces of its existence should be wiped; forgotten; erased. Newspapers bearing the date it was created should be destroyed; insects that spawned during its inception should be sought out and eradicated. Lo! the very binary impulses which signalled its data should be systematically removed and undone; the pixels it occupied on the screens it ran on should become blackened and empty. A cold, dead world should surround the land where its functions and keywords took shape, where nothing shall grow and old men fear to tread. A fell voice on the air should whisper ominous warnings and shadowy threats to any soul that ever speaks of it in the days and years to come.

:+1:

**Comment by wpf500** [comment]
image

**Comment by wpf500** [comment]
Never forget it now

**Comment by davidrapson** [comment]
Look OK to you @jamesoram ?

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
