### PR TITLE
Hide global header and footer when in app

### PR DESCRIPTION
**Pull request by GHaberis**

### CODE REVIEW

**Comment by GHaberis** [comment]
@rtyley @paulbrown1982

**Comment by rtyley** [comment]
@GHaberis could you link this PR to the related PRs in the mobile repos?

**Comment by GHaberis** [comment]
@rtyley here they are https://github.com/guardian/ios-live/pull/2247 and https://github.com/guardian/android-news-app/pull/2821

**Comment by paulbrown1982** [comment]
:+1:

**Pull request merged**
