### PR TITLE
Enable button for paid-to-paid upgrades

### PR DESCRIPTION
**Pull request by davidrapson**
Got the go ahead from Jason to enable the button for paid-to-paid upgrades.

screen shot 2015-02-17 at 10 36 47

### CODE REVIEW

**Comment by davidrapson** [comment]
@feedmypixel Mind giving this a once-over, would be good to get this out in time for the demo.

**Comment by feedmypixel** [comment]
:+1: 
As a side note is it me or is this file doing a little to much?

**Comment by davidrapson** [comment]
@feedmypixel Yep, but this is the file that's about to go once the new change/cancel/downgrade pages come in.

**Comment by feedmypixel** [comment]
:metal:

**Pull request merged**
