### PR TITLE
Safari 5.1 compatibility fixes

### PR DESCRIPTION
**Pull request by davidrapson**
This PR fixes a few issues which were preventing users in Safari 5.1 from signing up as members due to JavaScript errors.

* Bonzo `.hide()` causing a fatal error, switched to toggling class names instead of using show/hide.
* Fixes layout issues due to missing `calc` support.
* Don't use `type=tel` to trigger numeric inputs: causes noise in Safari 5.1, but is also incorrect usage as we were not using for telephone fields. Prefer plain text input with numeric pattern

**Successful payment**

screen shot 2015-04-02 at 17 20 53

**Fixed layout**

safari-after

**Previous broken layout**

screen shot 2015-04-02 at 17 31 20

### CODE REVIEW

**Comment by mattandrews** [comment]
All good :+1: 

Nice job figuring out the causes of these issues as well, some smart work here.

**Comment by davidrapson** [comment]
@jamesoram Look OK to you?

**Comment by davidrapson** [comment]
Ran functional test suite and all passed.

screen shot 2015-04-07 at 12 19 33

**Comment by davidrapson** [comment]
Confirmed on PROD using test-user in Safari 5.1

screen shot 2015-04-07 at 13 05 03

**Pull request merged**
