### PR TITLE
Include promotion info on the thank you page

### PR DESCRIPTION
**Pull request by tomverran**
This is a pretty basic implementation but hopefully is good enough for now

image

### CODE REVIEW

**Comment by tomverran** [comment]
@AWare

**Comment by AWare** [comment]
We want to show redemptionInstructions along with the description on the thankyou page. 
Also, maybe the tick box? http://8r81uk.axshare.com/#p=mem-thank_you-partner-annual

**Comment by AWare** [comment]
:+1:

**Comment by tomverran** [comment]
Well it works for me :crying_cat_face: 

image

**Pull request merged**
