### PR TITLE
Fix staff signup form

### PR DESCRIPTION
**Pull request by mattandrews**
This ~~~insane~~~ change fixes broken layouts:

#### Before:

screen shot 2015-01-22 at 17 44 50

#### After:

screen shot 2015-01-22 at 17 46 21

### CODE REVIEW

**Comment by feedmypixel** [comment]
is this effecting other forms?

**Comment by feedmypixel** [comment]
> is this effecting other forms?

(quick search) nope :+1:

**Comment by mattandrews** [comment]
Okay with you @jamesoram?

**Comment by wpf500** [comment]
:+1:

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
