### PR TITLE
Use new version of membership-common for failed timing logging

### PR DESCRIPTION
**Pull request by wpf500**
This version of `membership-common` will log failed `Future`s that are wrapped in `Timing.record`, useful for seeing when requests are failing and also how long failed requests took.

image

### CODE REVIEW

**Comment by rtyley** [comment]
Looks good to me - don't forget to update [membership-workflow](https://github.com/guardian/membership-workflow/blob/deb1704d/project/Dependencies.scala#L8) too! :+1:

**Comment by jennysivapalan** [comment]
:-1:

**Comment by jennysivapalan** [comment]
oops sorry

**Comment by jennysivapalan** [comment]
I didn't meant to do that! :+1:

**Comment by mattandrews** [comment]
:-1: to @jennysivapalan

**Pull request merged**
