### PR TITLE
Use membership-common 0.99

### PR DESCRIPTION
**Pull request by tomverran**
The deleted config files are in membership-common these days
Also had to update the zuora SOAP / REST configs

### CODE REVIEW

**Comment by tomverran** [comment]
@rtyley would you mind taking a look over this? Thanks!

**Comment by rtyley** [comment]
This relates to https://github.com/guardian/membership-common/pull/101

**Comment by rtyley** [comment]
This is cool, do it for subscriptions-frontend at the same time tho!

**Comment by tomverran** [comment]
image

Sign up / upgrade flows worked and used the UAT account

**Pull request merged**
