### PR TITLE
Keep event detail image within tablet margins

### PR DESCRIPTION
**Pull request by joelochlann**
... and also add left padding to the caption

#### Before
picture 64

#### After
picture 65

### CODE REVIEW

**Comment by tomverran** [comment]
should that book tickets arrow not be on the same line as the text?

**Comment by joelochlann** [comment]
@tomverran Well, yes. There are a few other niggles too - placement of the Guardian Live roundel in smaller viewports. Separate PRs I think. I will do one for the button right now. But OK to merge this one?

**Comment by tomverran** [comment]
ah yep fair enough :+1:

**Comment by joelochlann** [comment]
just trying to get my PR count up :stuck_out_tongue_winking_eye:

**Pull request merged**
