### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by joelochlann**
This fixes a few bits and bobs but most importantly makes it clear that you don't need to run up Identity API locally to get this project up and running.

### CODE REVIEW

**Comment by joelochlann** [comment]
@davidrapson @tomverran

**Comment by tomverran** [comment]
:+1: looks good

**Comment by joelochlann** [comment]
@tomverran @davidrapson Sorry, should've merged & opened a new PR but I've ended up stuffing a few more commits into this one. Worth having another look. It now also includes a few extra bits of info on NGINX and splits the NGINX info into its own readme, like frontend does.

**Comment by davidrapson** [comment]
:+1: LGTM

**Comment by joelochlann** [comment]
@rtyley You may want to have a quick look at this too

**Pull request merged**
