### PR TITLE
Abstract images/metadata out into ResponsiveImageGroup object

### PR DESCRIPTION
**Pull request by davidrapson**
Removes duplication from `RichEvent` and `MembersOnlyContent` so that the generation of `ResponsiveImageGroups` is centralised for Grid and CAPI images.

screen shot 2015-03-18 at 15 28 35

screen shot 2015-03-18 at 15 28 44

@feedmypixel This now leaves `MembersOnlyContent` being pretty light so might be worth having a quick chat about how we use it.

/cc @rtyley

### CODE REVIEW

**Comment by mattandrews** [comment]
Great work doing all this Scala – looks good to me! :+1:

**Comment by davidrapson** [comment]
Totally going to take all the credit for this, definitely no help from @rtyley

**Comment by davidrapson** [comment]
@jamesoram Mind giving a quick once over of the event image, just confirming that they show OK.

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
